image_name = "alexpoo/task-10"
replicas_count = "3"
container_name = "static-site"
app_name = "static-site"
service_name = "static-site-loadbalancer"
deployment_name = "static-deployment"
token = "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"