#- name: test shell
#  shell: curl -X POST -u admin:1239 http://localhost:8080/exit

#- name: mkdir
#  file:
#    path: /var/lib/jenkins/jobs/final/
#    state: directory
#    owner: jenkins
#    group: jenkins
#  
#- name: copy job xml
#  copy:
#    src: /root/roles/jenkins/templates/final.xml
#    dest: /var/lib/jenkins/jobs/final/final.xml
#    owner: jenkins
#    group: jenkins

#- name: start Jenkins
#  become: yes
#  sysvinit:
#    name: jenkins
#    state: started  


#- name: Wait for Jenkins to start up before proceeding.
#  uri:
#    url: "http://localhost:8080"
#    method: GET
#    return_content: "yes"
#    timeout: 5
#    body_format: raw
#    follow_redirects: "no"
#    status_code: 200,403
#  register: result
#  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
#  retries: 60
#  delay: 5
#  changed_when: false
#  check_mode: false


#- name: Create a jenkins job
#  jenkins_job:
#    config: "{{ lookup('file', 'jobs/final/config.xml') }}"
#    name: final
#    password: 1239
#    url: http://localhost:8080
#    user: admin
#    state: present
#    #validate_certs: no

#- name: Create a jenkins build 
# community.general.jenkins_build:
#   name: "final"
#    build_number: 1
#    state: present
#    user: admin
#    password: 1239
#    url: http://localhost:8080