- name: Install plugins for jenkins
  community.general.jenkins_plugin:
    #jenkins_home: /var/lib/jenkins
    name: "{{ item }}"
    timeout: 180
    url_username: admin
    url_password: 1239
    url: http://localhost:8080
    with_dependencies: yes
    state: present
    #use_proxy: no
    updates_url: https://gruenehoelle.nl
  loop:
   - nexus-artifact-uploader
   - credentials
   - git
   - github
   - golang
   - pipeline
   - ssh
   - ssh-credentials
   - ssh-build-agents
   - workflow-cps
   - workflow-aggregator
   - pipeline-stage-view
   - pipeline-stage-step
   - pipeline-github-lib  
   - docker-workflow
   - docker-pipeline
   - docker-workflow
   - docker-build-step
   - docker-plugin
  register: plugin_result
  until: plugin_result is success
  retries: 20
  delay: 1


#- name: stop Jenkins
#  shell: killall -u jenkins
#
#- name: start Jenkins
#  become: yes
#  sysvinit:
#    name: jenkins
#    state: started  


#- name: Wait for Jenkins to start up before proceeding.
#  uri:
#    url: "http://localhost:8080"
#    method: GET
#    return_content: "yes"
#    timeout: 5
#    body_format: raw
#    follow_redirects: "no"
#    status_code: 200,403
#  register: result
#  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
#  retries: 60
#  delay: 5
#  changed_when: false
#  check_mode: false