- name: Install plugins for jenkins
  community.general.jenkins_plugin:
    #jenkins_home: /var/lib/jenkins
    name: "{{ item }}"
    timeout: 180
    url_username: admin
    url_password: 1239
    url: http://localhost:8080
    with_dependencies: yes
    state: present
    #use_proxy: no
    updates_url: https://gruenehoelle.nl
  loop:
   - nexus-artifact-uploader
   - credentials
   - git
   - github
   - golang
   - pipeline
   - ssh
   - ssh-credentials
   - ssh-build-agents
   - workflow-cps
   - workflow-aggregator
   - pipeline-stage-view
   - pipeline-stage-step
   - pipeline-github-lib  
   - docker-workflow
   - docker-pipeline
   - docker-workflow
   - docker-build-step
   - docker-plugin
   - startup-trigger-plugin
  register: plugin_result
  until: plugin_result is success
  retries: 20
  delay: 1
