Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11" 
    #ansible collection needs Ansible 2.9 version for this reason we use debian11 (debian 10 - Ansible 2.7.7)
    
    
  
    config.vm.define "production.vm" do |node|
      node.vm.network "private_network", ip: "192.168.56.12"
      node.vm.provider("virtualbox") { |vb| vb.memory = 512 }
    end
  
    config.vm.define "nexus.vm" do |node|
      node.vm.network "private_network", ip: "192.168.56.10"
      node.vm.provider("virtualbox") { |vb| vb.memory = 3072 }
    end
    
    config.vm.define "staging.vm" do |node|
      node.vm.network "private_network", ip: "192.168.56.11"
      node.vm.provider("virtualbox") { |vb| vb.memory = 512 }
    end
  
    config.vm.define "jenkins.vm" do |node|
      node.vm.network "private_network", ip: "192.168.56.9"
      node.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
      
  
      node.vm.provision :file, source: '.vagrant/machines/production.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_production.vm'
      node.vm.provision :file, source: '.vagrant/machines/nexus.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_nexus.vm'
      node.vm.provision :file, source: '.vagrant/machines/staging.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_staging.vm'
      node.vm.provision :file, source: 'inventory/hosts', destination: 'inventory/hosts'
  
      config.vm.synced_folder ".", "/vagrant"
      #config.vm.synced_folder "./roles", "/etc/ansible/roles"
      #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      #config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  
      node.vm.provision "shell", inline: <<-shell 
        chmod =600 /home/vagrant/.ssh/private_key_staging.vm
        chmod =600 /home/vagrant/.ssh/private_key_nexus.vm
        chmod =600 /home/vagrant/.ssh/private_key_production.vm
        shell
  
      node.vm.provision :ansible_local do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.inventory_path = "inventory/hosts" 
        ansible.limit = "all"
        ansible.galaxy_command = "ansible-galaxy collection install -r%{role_file} --force"
        ansible.galaxy_role_file = 'requirements.yaml'
        
      end
    end
  end