---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: DockerfileJenkins
    image: jenkins
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - workspace:/var/lib/jenkins/workspace/
    ports:
      - 8080:8080
    network_mode: host
    container_name: jenkins


  nexus:
    build:
      context: .
      dockerfile: DockerfileNexus
    ports:
      - 8081:8081
    network_mode: host
    image: nexus
    container_name: nexus

volumes:
  workspace:
