---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: DockerfileJenkins
    image: jenkins
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - workspace:/var/lib/jenkins/workspace/
    ports:
      - 8080:8080
    network_mode: host
    #networks:
    #  test: 
    #    ipv4_address: 192.168.56.3
    container_name: jenkins


  nexus:
    build:
      context: .
      dockerfile: DockerfileNexus
    ports:
      - 8081:8081
    network_mode: host
    #networks:
    #  test: 
    #   ipv4_address: 192.168.56.2
    image: nexus
    container_name: nexus

#networks:
# test:
#  driver: bridge
#  ipam:
#    config:
#     - subnet: 192.168.56.0/24
volumes:
  workspace:
