# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  config.vm.network "private_network", ip: "192.168.56.9"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = 3072
    vb.cpus   = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release
    apt-get update
    apt-get install -y docker.io docker-compose
    usermod -aG docker vagrant
    sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
    sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
    cd /vagrant/
    docker-compose up
  SHELL
end
