---
#Playbook local
- name: puppet
  hosts: all
  tasks:

- hosts: master
  become: yes
  become_user: root
  tasks:
  - name: repo add
    become: yes
    #become_user: root
    shell: |
      wget -P /vagrant/ https://apt.puppet.com/puppet7-release-buster.deb 
      sudo dpkg -i /vagrant/puppet7-release-buster.deb
        
  - name: install packages
    become: yes
    #become_user: root
    apt:
     pkg:
     - puppetserver
     - r10k
     state: present

  - name: get the ppsrvconf
    become: yes
    shell: |
     wget -O /etc/default/puppetserver https://raw.githubusercontent.com/aleexpo/puppet-server-repo/production/templates/puppetserver 

  - name: changes puppet.conf
    become: yes
    blockinfile:
     path: /etc/puppetlabs/puppet/puppet.conf
     block: |
      autosign = true
      server = master.puppet
      [main]
      server = master.puppet
      certname = master.puppet
      environment = production
      [master]
      dns_alt_names = master.puppet

  - name: ip addresses add in hosts
    become: yes
    blockinfile:
     path: /etc/hosts
     block: |
      192.168.56.9 slave1
      192.168.56.10 slave2
      192.168.56.11 master.puppet

  - name: start puppet server
    become: yes
    service:
      name: puppetserver
      state: started

  - name: enable puppetserver
    become: yes
    service:
       name: puppetserver
       enabled: yes

  - name: create directory
    become: yes
    file: 
      path: /etc/puppetlabs/r10k/
      state: directory

  - name: get the r10k.yaml
    become: yes
    shell: |
     wget -P /etc/puppetlabs/r10k/ https://raw.githubusercontent.com/aleexpo/puppet-server-repo/production/templates/r10k.yaml 
     
#configuring slave machines
     
- hosts: slaves
  tasks:

  - name: repo add
    become: yes
    shell: |
      wget -O /vagrant/ https://apt.puppet.com/puppet7-release-buster.deb 
      dpkg -i /vagrant/puppet7-release-buster.deb

  - name: puppet-agent install
    become: yes
    become_user: root
    apt:
      pkg:
      - puppet-agent

  - name: ip addresses add in hosts
    become: yes
    blockinfile:
      path: /etc/hosts
      block: |
       192.168.56.9 slave1
       192.168.56.10 slave2
       192.168.56.11 master.puppet    

  - name: agent config add
    become: yes
    blockinfile:
      path: /etc/puppetlabs/puppet/puppet.conf
      block: |
       [agent]
       server = master.puppet
       runinterval = 1m
       [main]
       certname = {{inventory_hostname}}
  
  - name: start puppetagent
    become: yes
    service:
      name: puppet
      state: started
 
  - name: enable puppetagent
    become: yes
    service:
     name: puppet
     enabled: yes     