---
#Playbook local
- name: puppet
  hosts: all
  tasks:

- hosts: master
  become: yes
  become_user: root
  tasks:

  - name: install repo
    become: yes
    apt:
     deb: https://apt.puppet.com/puppet7-release-buster.deb 
      
  - name: install packages
    become: yes
    apt:
     pkg:
     - puppetserver
     - r10k
     - puppet-agent
     state: present
     update_cache: yes

  - name: get the ppsrvconf
    become: yes
    get_url:
      force: yes
      url: https://raw.githubusercontent.com/aleexpo/devops-hometasks/main/task-04/templates/puppetserver
      dest: /etc/default/puppetserver   
  
  - name: changes puppet.conf
    become: yes
    blockinfile:
     path: /etc/puppetlabs/puppet/puppet.conf
     block: |
      autosign = true
      server = master.puppet
      [main]
      server = master.puppet
      certname = master.puppet
      environment = production
      [master]
      dns_alt_names = master.puppet
      [agent]
      server = master.puppet
      runinterval = 1m
  
  - name: ip addresses add in hosts
    become: yes
    blockinfile:
     path: /etc/hosts
     block: |
      192.168.56.9 slave1
      192.168.56.10 slave2
      192.168.56.11 master.puppet
      192.168.56.12 mineserver.puppet 
  - name: start puppet server
    become: yes
    service:
     name: puppetserver
     state: started

  - name: start puppet agent
    become: yes
    service:
     name: puppet
     state: started    

  - name: enable puppetagent
    become: yes
    service:
     name: puppet
     enabled: yes         
  
  - name: enable puppetserver
    become: yes
    service:
     name: puppetserver
     enabled: yes
  
  - name: create directory
    become: yes
    file: 
     path: /etc/puppetlabs/r10k/
     state: directory
  
  - name: get the r10k.yaml
    become: yes
    get_url:
     url: https://raw.githubusercontent.com/aleexpo/devops-hometasks/main/task-04/templates/r10k.yaml
     dest: /etc/puppetlabs/r10k/   

  - name: auto deploy environment(cron)
    cron:
     name: "deploy environment"
     minute: "0-59"
     hour: "*"
     job: "sudo r10k deploy environment -p"

  #configuring slave machines
     
- hosts: slaves, mineserver
  tasks:
  
  - name: install repo
    become: yes
    apt:
      deb: https://apt.puppet.com/puppet7-release-buster.deb
  
  - name: puppet-agent install
    become: yes
    become_user: root
    apt:
     pkg:
     - puppet-agent
     state: present
     update_cache: yes
  
  - name: ip addresses add in hosts
    become: yes
    blockinfile:
     path: /etc/hosts
     block: |
      192.168.56.9 slave1
      192.168.56.10 slave2
      192.168.56.11 master.puppet 
      192.168.56.12 mineserver.puppet   
  
  - name: agent config add
    become: yes
    blockinfile:
     path: /etc/puppetlabs/puppet/puppet.conf
     block: |
      [agent]
      server = master.puppet
      runinterval = 1m
      [main]
      certname = {{inventory_hostname}}
  
  - name: start puppetagent
    become: yes
    service:
     name: puppet
     state: started
  
  - name: enable puppetagent
    become: yes
    service:
     name: puppet
     enabled: yes     
