#-*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "bytesguy/debian-10-arm64"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  
  config.vm.provider "vmware_fusion" do |vm|
     # Display the VirtualBox GUI when booting the machine
     #vm.gui = true
     vm.memory = "512"
   end

   
  config.vm.define "vm1" do |vm1|
     #vm1.vm.network "private_network", ip: "192.168.0.110"
   
    vm1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.become = true
    end
  end
end  